import = [
    'C:\Users\Hexin\Documents\Repositories\aarowill\base16-alacritty\colors\base16-tomorrow-night-eighties-256.toml',
]

[shell]
program = 'C:\Windows\system32\wsl.exe'
args = [
    '--cd',
    '~',
    '--distribution',
    'arch',
    '--exec',
    '/bin/zsh',
    '-c',
    '"tmux new -A && exec zsh -i"',
]

[window]
dimensions = { columns = 160, lines = 48 }
position = { x = 0 , y = 0 }
dynamic_padding = true
dynamic_title = false
decorations = 'None'

[font]
normal = { family = 'HackGen Console NF', style = 'Regular' }
offset = { x = 1, y = 0 }

[cursor]
style = { shape = 'Beam', blinking = 'Off' }
vi_mode_style  = { shape = 'Block', blinking = 'Off' }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = 'Q', mods = 'Control', mode = 'Vi', action = 'Quit' },
    { key = 'Escape', mode = 'Vi|~Search', action = 'ToggleViMode' },
]

[[hints.enabled]]
command = { program = "cmd", args = [ "/c", "start", "" ] }
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
command = { program = "cmd", args = [ "/c", "start", "" ] }
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = 'G', mods = 'Shift|Control' }
regex = '[0-9a-f]{7,40}'
