#!/bin/zsh

declare -r dir=$(cd $(dirname $0) && pwd)/config

info() {
  printf "\e[39m$1\e[0m"
}

error() {
  printf "\e[1;31m$1\e[0m"
}

warning() {
  printf "\e[1;33m$1\e[0m"
}

path() {
  printf "\e[4m$1\e[24m"
}

make_symlink() {
  declare -r source=$dir/$1
  declare -r target=$2

  if [[ ! -L $target && -d $target ]]; then
    error "$(path $target) is directory.\n"
    return
  fi

  if [[ -L $target || -f $target ]]; then
    warning "$(path $target) already exists. overwrite? (y/N): "
    if ! read -q; then
      info "\n"
      return
    fi
    info "\n"
    unlink $target
  fi

  ln -s $source $target && info "Create symblic link: $(path $source) -> $(path $target)\n"
}

make_symlink zsh/.zshenv $HOME/.zshenv
source $HOME/.zshenv

mkdir -p $XDG_CONFIG_HOME
mkdir -p $XDG_CACHE_HOME
mkdir -p $XDG_CONFIG_HOME

make_symlink zsh $ZDOTDIR
make_symlink git $XDG_CONFIG_HOME/git
make_symlink nvim $XDG_CONFIG_HOME/nvim
