#!/bin/zsh

info() {
  printf "\e[39m$1\e[0m"
}

error() {
  printf "\e[1;31m$1\e[0m"
}

warning() {
  printf "\e[1;33m$1\e[0m"
}

path() {
  printf "\e[4m$1\e[24m"
}

make_symlink() {
  declare -r dir=$(cd $(dirname $0) && pwd)/config
  declare -r source=$dir/$1
  declare -r target=$2

  if [[ ! -L $target && -d $target ]]; then
    error "$(path $target) is directory.\n"
    return
  fi

  if [[ -L $target || -f $target ]]; then
    warning "$(path $target) already exists. overwrite? (y/N): "
    if ! read -q; then
      info "\n"
      return
    fi
    info "\n"
    unlink $target
  fi

  ln -s $source $target && info "Create symblic link: $(path $source) -> $(path $target)\n"
}

install_dotfiels() {
  make_symlink zsh/.zshenv $HOME/.zshenv
  source $HOME/.zshenv

  mkdir -p $XDG_CONFIG_HOME
  mkdir -p $XDG_CACHE_HOME
  mkdir -p $XDG_CONFIG_HOME

  make_symlink zsh $ZDOTDIR
  make_symlink git $XDG_CONFIG_HOME/git
  make_symlink nvim $XDG_CONFIG_HOME/nvim
  make_symlink fdignore $XDG_CONFIG_HOME/fdignore
}

install_plugin_managers() {
  declare -r github_repo=$1
  declare -r install_dir=$2

  if [[ -d $2 ]]; then
    error "$(path $install_dir) already exists.\n"
    return
  fi

  info "Installing $github_repo\n"
  git clone --depth=1 https://github.com/$github_repo $install_dir
  info "Done\n"
}

info ">>> Installing dotfiles\n"
install_dotfiels

info "\n"

info ">>> Installing plugin managers\n"
mkdir -p $XDG_CACHE_HOME/dein
install_plugin_managers Shougo/dein.vim $XDG_CACHE_HOME/dein/repos/github.com/Shougo/dein.vim
mkdir -p $XDG_CACHE_HOME/zinit
install_plugin_managers zdharma/zinit $XDG_CACHE_HOME/zinit/bin
