export PATH="/usr/local/sbin:$PATH"
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ZPLG_HOME=$XDG_CACHE_HOME/zplugin

declare -A ZPLGM
ZPLGM[HOME_DIR]=$XDG_CACHE_HOME/zplugin
ZPLGM[BIN_DIR]=$ZPLGM[HOME_DIR]/bin
ZPLGM[PLUGINS_DIR]=$ZPLGM[HOME_DIR]/plugins
ZPLGM[COMPLETIONS_DIR]=$ZPLGM[HOME_DIR]/completions
ZPLGM[SNIPPETS_DIR]=$ZPLGM[HOME_DIR]/snippets
export ZPLGM
