recipe:
  Rx: config/rime/recipes/schema
  args:
  description: schema recipe
install_files: >
  config/rime/__default.custom.yaml
  config/rime/terra_pinyin.custom.yaml
patch_files:
  default.custom.yaml:
    - patch/+:
      __include: __default.custom.yaml:/patch
